# Generated by Django 5.0.6 on 2024-07-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_ip", models.GenericIPAddressField()),
                ("text", models.TextField()),
                ("fps", models.PositiveSmallIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
